name: Set up a MongoDB Atlas cluster and run integration tests!

on: [push]
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3

      - name: Install npm packages
        uses: bahmutov/npm-install@v1

      - name: Set up a MongoDB Atlas M0 cluster and run tests
        env:
          MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
          MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_API_KEY }}
          MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_API_KEY }}
        run: |
          .github/actions-scripts/set-up-cluster-and-run-tests.sh
